[project]
name = "challenge-mle"
version = "0.1.0"
description = ""
authors = [
    {name = "DanielOspina2301",email = "daniel.alberto.ospina@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
[tool.poetry.dependencies]
fastapi = "^0.116.1"
pydantic = "^2.11.7"
uvicorn = "^0.35.0"
numpy = "^2.3.2"
pandas = "^2.3.1"
scikit-learn = "^1.7.1"
matplotlib = "^3.10.5"
seaborn = "^0.13.2"
xgboost = "^3.0.4"
google-cloud-storage = "^3.3.0"
google-cloud-bigquery = "^3.36.0"
pydantic-settings = "^2.10.1"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
